---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: https://api.stackbit.com/project/5e737eab0b968f0012bfbb32/webhook/forestry
sections:
- type: heading
  label: Pages
- type: document
  path: index.md
  label: Home
  templates:
  - home
- type: document
  path: about.md
  label: About
- type: document
  path: blog/index.md
  label: Blog
  templates:
  - blog
- type: document
  path: contact.md
  label: Contact
  templates:
  - contact
- type: document
  path: contact-submitted.md
  label: Contact Submitted
  match: "**/*"
- type: heading
  label: Blog
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - post
- type: directory
  path: projects
  label: Projects
  create: all
  match: "**/*"
  templates:
  - project
- type: heading
  label: Theme
- type: document
  path: _config.yml
  label: Global Site Config
  templates:
  - config
- type: document
  path: _data/social.json
  label: Social Links
  templates:
  - social
- type: document
  path: _data/author.json
  label: Author
  templates:
  - author
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
